dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
- provider: script
  skip_cleanup: true
  script:
  - curl -f -T matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -urobkovai:$BINTRAY_API_KEY "https://api.bintray.com/content/robkovai/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"